name: Build Native App

on:
  pull_request:
    branches: [dev]
    types: [opened, reopened]

jobs:
  build:
    if: github.head_ref == 'release-mobile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Build native app
        env:
          CAPGO_TOKEN: e65ec15a-e0d3-4192-937f-1d43a79dd80f
        run: |
          npx @capgo/cli@latest build com.capgo.mvp.ap \
            --platform both \
            --build-mode debug

#      - name: Build native app
#        env:
#          CAPGO_TOKEN: ${{ secrets.CAPGO_TOKEN }}
#        run: |
#          npx @capgo/cli@latest build nl.digibtw.app,nl.digibtw.knab \
#            --platform both \
#            --build-mode debug